{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Response Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_mixer_check_server_upstream_rq_time",
     "legendFormat": "{{ quantile }} (envoy Check)"
    },
    {
     "expr": "envoy_cluster_mixer_report_server_upstream_rq_time",
     "legendFormat": "{{ quantile }} (envoy Report)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_server_handling_seconds_bucket{}[1m])) by (grpc_method, le)) * 1000",
     "legendFormat": "{{ grpc_method }} 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(grpc_server_handling_seconds_bucket{}[1m])) by (grpc_method, le)) * 1000",
     "legendFormat": "{{ grpc_method }} 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{}[1m])) by (grpc_method, le)) * 1000",
     "legendFormat": "{{ grpc_method }} 0.99"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_mixer_check_server_upstream_rq_total[1m])",
     "legendFormat": "envoy (Check)"
    },
    {
     "expr": "rate(envoy_cluster_mixer_report_server_upstream_rq_total[1m])",
     "legendFormat": "envoy (Report)"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total[1m]))",
     "legendFormat": "mixer (Total)"
    },
    {
     "expr": "rate(grpc_server_handled_total[1m])",
     "legendFormat": "mixer ({{ grpc_method }})"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_mixer_check_server_membership_healthy",
     "legendFormat": "Healthy (mixer_check_server)"
    },
    {
     "expr": "envoy_cluster_mixer_check_server_membership_total",
     "legendFormat": "Total (mixer_check_server)"
    },
    {
     "expr": "envoy_cluster_mixer_report_server_membership_healthy",
     "legendFormat": "Healthy (mixer_report_server)"
    },
    {
     "expr": "envoy_cluster_mixer_report_server_membership_total",
     "legendFormat": "Total (mixer_report_server)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_mixer_check_server_upstream_cx_active",
     "legendFormat": "Active  (mixer_check_server)"
    },
    {
     "expr": "envoy_cluster_mixer_report_server_upstream_cx_active",
     "legendFormat": "Active  (mixer_report_server)"
    }
   ]
  },
  {
   "title": "Non-successes (4xxs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_mixer_check_server_upstream_rq_4xx[1m])",
     "legendFormat": "Envoy Check"
    },
    {
     "expr": "irate(envoy_cluster_mixer_report_server_upstream_rq_4xx[1m])",
     "legendFormat": "Envoy Report"
    },
    {
     "expr": "sum(irate(grpc_server_handled_total{grpc_code!=\"OK\",grpc_service=~\".*Mixer\"}[1m])) by (grpc_method)",
     "legendFormat": "Mixer {{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Server Error Rate (5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_mixer_check_server_upstream_rq_5xx[1m])",
     "legendFormat": "Envoy Check"
    },
    {
     "expr": "rate(envoy_cluster_mixer_report_server_upstream_rq_5xx[1m])",
     "legendFormat": "Envoy Report"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code=~\"Unknown|Unimplemented|Internal|DataLoss\"}[1m])) by (grpc_method)",
     "legendFormat": "Mixer {{ grpc_method }}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Adapter Dispatch Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(mixer_runtime_dispatch_duration_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p90 "
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p99"
    }
   ]
  },
  {
   "title": "Adapter Dispatch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mixer_runtime_dispatch_count{adapter=~\"$adapter\"}[1m])) by (adapter)",
     "legendFormat": "{{ adapter }}"
    }
   ]
  },
  {
   "title": "Outliers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_mixer_check_server_outlier_detection_ejections_enforced_total[1m])",
     "legendFormat": "Total Ejections (mixer_check_server)"
    },
    {
     "expr": "rate(envoy_cluster_mixer_check_server_outlier_detection_ejections_overflow[1m])",
     "legendFormat": "Overflow Ejections (mixer_check_server)"
    },
    {
     "expr": "envoy_cluster_mixer_check_server_outlier_detection_ejections_active",
     "legendFormat": "Active Ejections (mixer_check_server)"
    },
    {
     "expr": "rate(envoy_cluster_mixer_report_server_outlier_detection_ejections_enforced_total[1m])",
     "legendFormat": "Total Ejections (mixer_report_server)"
    },
    {
     "expr": "rate(envoy_cluster_mixer_report_server_outlier_detection_ejections_overflow[1m])",
     "legendFormat": "Overflow Ejections (mixer_report_server)"
    },
    {
     "expr": "envoy_cluster_mixer_report_server_outlier_detection_ejections_active",
     "legendFormat": "Active Ejections (mixer_report_server)"
    }
   ]
  },
  {
   "title": "Client Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_mixer_check_server_upstream_rq_retry[1m])",
     "legendFormat": "Total (mixer_check_server)"
    },
    {
     "expr": "irate(envoy_cluster_mixer_check_server_upstream_rq_retry_success[1m])",
     "legendFormat": "Success  (mixer_check_server)"
    },
    {
     "expr": "irate(envoy_cluster_mixer_check_server_upstream_rq_retry_overflow[1m])",
     "legendFormat": "Overflow  (mixer_check_server)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Instances in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_instance_config_count) by (configID)))",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_count) by (configID)))",
     "legendFormat": "Rules"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_error_count) by (configID)))",
     "legendFormat": "Config Errors"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_match_error_count) by (configID)))",
     "legendFormat": "Match Errors"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_unsatisfied_action_handler_count) by (configID)))",
     "legendFormat": "Unsatisfied Actions"
    }
   ]
  },
  {
   "title": "Handlers in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_handler_config_count) by (configID)))",
     "legendFormat": "Handlers"
    }
   ]
  },
  {
   "title": "Attributes in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_attribute_count) by (configID)))",
     "legendFormat": "Attributes"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Virtual Memory ({{ job }})"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Resident Memory ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Alloc ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Heap in-use ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Stack in-use ({{ job }})"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (service)",
     "legendFormat": "{{ service }} total (k8s)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (container_name, service)",
     "legendFormat": "{{ service }} - {{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Number of Goroutines ({{ job }})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}[1m])) by (pod_name), \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")",
     "legendFormat": "{{ service }} total (k8s)"
    },
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}[1m])) by (container_name, pod_name), \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")",
     "legendFormat": "{{ service }} - {{ container_name }} (k8s)"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=~\"istio-telemetry|istio-policy\"}[1m])) by (job)",
     "legendFormat": "{{ job }} (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (container_name, service)",
     "legendFormat": "{{ service }} - {{ container_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Dispatch Duration By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.5, sum(rate(mixer_runtime_dispatch_duration_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p50 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p90 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p99 - {{ handler_short }} (error: {{ error }})"
    }
   ]
  },
  {
   "title": "Dispatch Count By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mixer_runtime_dispatch_count{adapter=\"$adapter\"}[1m]),\"handler\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "{{ handler }} (error: {{  error }})"
    }
   ]
  }
 ]
}